[build]
  command = "npm run build && npm run export"
  publish = "out"

[[redirects]]
  from = "https://louienavarro.ml/*"
  to = "https://www.louienavarro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.louienavarro.ml/*"
  to = "https://www.louienavarro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://louienavarro.netlify.app/*"
  to = "https://www.louienavarro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200